// <auto-generated />
namespace EnterpriseWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmployeesColumnHireDateChangedFromDateTimeToDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmployeesColumnHireDateChangedFromDateTimeToDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202205241927488_EmployeesColumnHireDateChangedFromDateTimeToDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
